services:
  - type: web
    name: moxvid
    env: node
    plan: free
    rootDir: MOXViD
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
